### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by johndpope** [ppwwyyxx/SoPaper#11]
```shell
sopaper "Distinctive image features from scale-invariant keypoints"
Traceback (most recent call last):
  File "/Users/jpope/miniconda3/envs/tf10/bin/sopaper", line 7, in <module>
    from sopaper.__main__ import main
  File "/Users/jpope/miniconda3/envs/tf10/lib/python3.7/site-packages/sopaper/__main__.py", line 23, in <module>
    from sopaper import searcher
  File "/Users/jpope/miniconda3/envs/tf10/lib/python3.7/site-packages/sopaper/searcher/__init__.py", line 8, in <module>
    from ..lib.ukutil import import_all_modules
  File "/Users/jpope/miniconda3/envs/tf10/lib/python3.7/site-packages/sopaper/lib/ukutil.py", line 76
    print check_filetype(open("./ukconfig.py").read(), 'PDF')
                       ^
SyntaxError: invalid syntax
```

I'm using python2

brew install poppler
Error: poppler 0.56.0 is already installed
To upgrade to 0.71.0, run `brew upgrade poppler`

seems to fix things.

**Comment by johndpope** [comment]
still not sure why this is not finding though
check_filetype !=check_file_type
<img width="935" alt="screen shot 2018-11-02 at 5 12 23 pm" src="https://user-images.githubusercontent.com/289994/47940894-7ef7f080-dec2-11e8-8178-2906735fe6f5.png">
